config/routes.rb
RubyBlog::Application.routes.draw do
  root :to  => 'blog_posts#index'

  get  'post'      => 'blog_posts#show',    :as => 'post'
  get  'posts'     => 'blog_posts#index',   :as => 'posts'
  get  'new_post'  => 'blog_posts#new',     :as => 'new_post'
  get  'edit_post' => 'blog_posts#edit',    :as => 'edit_post'
  get  'del_post'  => 'blog_posts#destroy', :as => 'del_post'
  post 'like_post' => 'blog_posts#like',    :as => 'like_post'
  resources :blog_posts

  get  'sign_up' => 'users#new',   :as => 'sign_up'
  get  'authors' => 'users#index', :as => 'authors'
  get  'profile' => 'users#show',  :as => 'profile'
  post 'set_name' => 'users#set_name', :as => 'set_name'
  put  'set_name' => 'users#set_name', :as => 'set_name'
  resources :users

  get  'log_in'   => 'sessions#new',     :as => 'log_in'
  get  'log_out'  => 'sessions#destroy', :as => 'log_out'
  resources :sessions

end

app/models/blog_post.rb
class BlogPost < ActiveRecord::Base
  attr_accessible :body, :title, :likes, :owner, :category, :category_id
  belongs_to :owner, :class_name => 'User'
  belongs_to :category, :class_name => 'Category'

  validates_presence_of :category
  validates_presence_of :owner
  validates_presence_of :title
  validates_presence_of :body
end

app/models/category.rb
class Category < ActiveRecord::Base
  attr_accessible :name
  validates_uniqueness_of :name
end

app/models/user.rb
class User < ActiveRecord::Base
  attr_accessible :email,
                  :password,
                  :password_confirmation,
                  :first_name,
                  :last_name

  #attr_accessor :first_name
  #before_save :set_default_first_name
  #
  #attr_accessor :last_name
  #before_save :set_default_last_name

  attr_accessor :password
  before_save :encrypt_password

  validates_confirmation_of :password
  validates_presence_of :password, :on => :create
  validates_presence_of :email
  validates_uniqueness_of :email

  def self.authenticate(email, password)
    user = find_by_email(email)
    if user && user.password_hash == BCrypt::Engine.hash_secret(password, user.password_salt)
      user
    else
      nil
    end
  end

  def encrypt_password
    if password.present?
      self.password_salt = BCrypt::Engine.generate_salt
      self.password_hash = BCrypt::Engine.hash_secret(password, password_salt)
    end
  end

  #def set_default_first_name
  #  if !(self.first_name)
  #    self.first_name = 'Mr.'
  #  end
  #end
  #
  #def set_default_last_name
  #  if !(self.last_name)
  #    self.last_name  = self.email
  #  end
  #end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery

  helper_method :current_user
  helper_method :categories

private
  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end

  def categories
    @categories = Category.all
  end
end

app/controllers/blog_posts_controller.rb
class BlogPostsController < ApplicationController

  def index
    cat_id = params[:category_id]
    if cat_id
      @blog_posts = BlogPost.where('category_id = ? ', cat_id)
      @blog_posts = @blog_posts.sort {|a, b| b.created_at <=> a.created_at}
    else
      @blog_posts = BlogPost.all
      @blog_posts = @blog_posts.sort {|a, b| b.created_at <=> a.created_at}
    end
    @chapter = "home"
  end

  def show
    @blog_post = BlogPost.find(params[:id])
  end

  def new
    @blog_post = BlogPost.new
  end

  def create
    @blog_post = BlogPost.new(params[:blog_post])
    @blog_post.owner = current_user
    @blog_post.category = Category.find(params[:category_id])
    @blog_post.likes = 0

    if current_user && @blog_post.save
      redirect_to @blog_post, notice: 'Blog post was successfully created.'
    else
      render action: 'new'
    end
  end

  def edit
    @blog_post = BlogPost.find(params[:id])
  end

  def update
    @blog_post = BlogPost.find(params[:id])
    if @blog_post.owner != current_user
      redirect_to posts_url, notice: 'Security violation'
      return
    end
    @blog_post.category = Category.find(params[:category_id])

    if @blog_post.update_attributes(params[:blog_post])
      redirect_to @blog_post, notice: 'Blog post was successfully updated. Check it out.'
    else
      render action: 'edit'
    end
  end

  def like
    @result = 0
    blog_post = BlogPost.find(params[:id])
    if blog_post.owner != current_user
      blog_post.likes += 1
      blog_post.save
      @result = 1
    end
    render :file => 'blog_posts/like.json.erb', :content_type => 'application/json'
  end

  def destroy
    @blog_post = BlogPost.find(params[:id])
    if @blog_post.owner != current_user
      redirect_to posts_url, notice: 'Security violation'
      return
    end
    @blog_post.destroy
    redirect_to posts_url
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    user = User.authenticate(params[:email], params[:password])
    if user
      session[:user_id] = user.id
      redirect_to root_url, :notice => 'Logged in!'
    else
      redirect_to root_url, :notice => 'Invalid email or password!'
    end
  end

  def destroy
    session[:user_id] = nil
    redirect_to root_url, :notice => 'Logged out!'
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def index
    @users = User.all
    @chapter = 'authors'
  end

  def new
    @user = User.new
    @chapter = 'sign_up'
  end

  def create
    @user = User.new(params[:user])
    if @user.save
      redirect_to root_url, :notice => 'Signed up!'
    else
      render 'new'
    end
  end

  def show
    @user = User.find(current_user)
    @chapter = 'profile'
  end

  def set_name
    @user = User.find(current_user)
    if @user.update_attributes(params[:user])
      redirect_to @user, notice: 'Name was successfully updated. Check it out.'
    else
      render action: 'show'
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/blog_posts_helper.rb
module BlogPostsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/blog_posts/_form.html.erb
<%= form_for(@blog_post) do |f| %>
  <% if @blog_post.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@blog_post.errors.count, 'error') %> prohibited this blog_post from being saved:</h2>

      <ul>
      <% @blog_post.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>


  <div class="edit_post" >
    <%= f.text_field :title  %>
    <div class="edit_category_holder">
      <% categories_array = categories.map { |category| [category.name, category.id] } %>
      <% category = 1 %>
      <% categories_options = options_for_select(categories_array, category) %>
      <%= select_tag :category_id, categories_options %>
    </div>
    <%= f.text_area :body %>
    <div class="submit">
        <%= f.submit "Send"%>
    </div>
  </div>
<% end %>

app/views/blog_posts/edit.html.erb
<div class="edit_header">
  <h1>Edit this post</h1>
  <%= link_to '← Home', blog_posts_path %>
</div>
<div class="edit_post">
  <%= render 'form' %>
</div>

app/views/blog_posts/index.html.erb
<% if current_user %>
  <div class="new_post_link_holder">
    <%= link_to 'Write a new post', new_post_path %>
  </div>
<% end %>
<% @blog_posts.each do |post| %>
  <div class="post_section">
    <div class="post_title">
      <h2><%= post.title %></h2>
    </div>

    <div class="post_content">
      <p><%= post.body %></p>
    </div>

    <div class="post_data">
      <%= link_to 'Read whole post', post %>
      <% if post.owner == current_user %>
        |
        <%= link_to 'Edit', edit_post_path(:id => post.id) %>  |
        <%= link_to 'Delete', del_post_path(:id => post.id) %>
      <% end %>
      <br/>
      &gt; <%= post.created_at.to_time.strftime('%B %e at %l:%M %p') %> |
      <strong>Author:</strong>
        <% if post.owner.first_name %>
          <%= post.owner.first_name %>
        <% else %>
          <%= post.owner.email %>
        <% end %>
         |
      <strong>Category:</strong>
      <%= link_to post.category.name, posts_path(:category_id => post.category.id) %>
    </div>

    <div class="post_likes" id="like_for_<%= post.id %>">
      <span><%= post.likes %></span>
    </div>
  </div>
<% end %>

app/views/blog_posts/like.json.erb
{"success" : <%= @result %>}

app/views/blog_posts/new.html.erb
<div class="edit_header">
  <h1>New blog post</h1>
  <%= link_to '← Home', blog_posts_path %>
</div>
<div class="edit_post">
  <%= render 'form' %>
</div>

app/views/blog_posts/show.html.erb
<div id="notice">
  <h2><%= notice %></p>
</div>


<div class="show_post">
  <div class="post_title">
    <h1> <%= @blog_post.title %> </h1>
  </div>
  <div class="post_content">
    <p><%= @blog_post.body %></p>
  </div>
  <div class="button_holder">
    <%= link_to '← Home', blog_posts_path %><%= link_to 'Edit →', edit_blog_post_path(@blog_post) %>
  </div>
</div>

app/views/layouts/_slider.html.erb
<!-- Slider Block -->
<div id="slider_holder">
  <div id="slider">
    <!-- List of slides -->
    <ul id="sliderContent">
      <li class="sliderImage">
        <%= image_tag('slider/1.jpg', :alt => "1" ) %>
        <span class="top"><strong>Ruby Is Fast</strong><br />Ruby provides a benchmarking library to make your job easy. The 'benchmark' library provides a few classes that will automatically benchmark your code and allow you to inspect the results.</span>
      </li>
      <li class="sliderImage">
        <%= image_tag('slider/2.jpg', :alt => "2" ) %>
        <span class="bottom"><strong>Ruby Is Secure</strong><br />Security vulnerabilities should be reported via an email to security@ruby-lang.org</span>
      </li>
      <li class="sliderImage">
        <%= image_tag('slider/3.jpg', :alt => "3" ) %>
        <span class="left"><strong>Ruby Is Robust</strong><br />You can certainly build robust business applications with Rails</span>
      </li>
      <li class="sliderImage">
        <%= image_tag('slider/4.jpg', :alt => "4" ) %>
        <span class="right"><strong>Ruby Is Friendly</strong><br />The famous Hello World  program is trivial in Ruby.</span>
      </li>
      <li class="clear sliderImage"></li>
    </ul>
  </div>
</div>

app/views/layouts/_textlogo.html.erb
<div id="logo_wrapper">
  <!-- Logo placeholder -->
  <div id="site_title">
    <h1>
      <a href="#">Ruby <strong>on Rails</strong><span>A Programmer's Best Friend</span></a>
    </h1>
  </div>
</div>

app/views/layouts/_topheader.html.erb
<script type="text/javascript">
    var chapter = "<%= @chapter %>";
</script>

<div id="top_header">
  <!-- Top main menu block -->
  <div id="menu">
    <ul class="main">
      <li><%= link_to 'Home',    root_path, :id => 'header_menu_home'    %></li>

      <% if current_user %>
        <li><%= link_to 'My profile', profile_path, :id => 'header_menu_profile' %></li>
      <% else %>
        <li><%= link_to 'Sign up', sign_up_path, :id => 'header_menu_sign_up' %></li>
      <% end %>
    </ul>
    <ul>
      <li><%= link_to 'Authors', authors_path, :id => 'header_menu_authors' %></li>
      <li><%= link_to 'About us', 'http://www.ruby-lang.org/en/about/', :id => 'header_menu_help' %></li>

      <% if !current_user %>
          <li><%= link_to 'Login', '#', :id => 'header_menu_sign_in' %></li>
      <% else %>
          <li><%= link_to 'Logout', log_out_path, :id => 'header_menu_sign_out' %></li>
      <% end %>

    </ul>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8"/>
  <meta name="keywords" content="Blog about Ruby on Rails" />
  <meta name="description" content="Just another blog about Ruby on Rails" />
  <%= csrf_meta_tag %>

  <%= stylesheet_link_tag 'application', :media => 'all' %>
  <%= javascript_include_tag 'application' %>

  <title>Blog about Ruby on Rails</title>
</head>

<body>
<div id="body_wrapper"> <!-- global wrapper -->

<%= render :partial => 'layouts/topheader' %>

<div id="outside_wrapper">

  <% if !current_user %>
      <%= render :partial => 'sessions/signin_popup' %>
  <% end %>

  <!-- image on top -->
  <%= image_tag 'ruby.png', :class => 'ruby' %>

  <div id="wrapper">
    <!-- Left side column -->
    <div id="left_column">
      <%= render :partial => 'layouts/textlogo' %>

      <!-- Side menu -->
      <div id="sidebar">
        <h4>Categories</h4>
        <ul class="list">
          <% categories.each do |category| %>
            <li><%= link_to category.name, posts_path(:category_id => category.id) %></li>
          <% end %>
        </ul>
      </div>
      <div class="clear"></div>
    </div>

    <!-- Slider block if necessary -->
    <% if !@hide_slider %>
        <%= render(:partial => 'layouts/slider') %>
    <% end %>

    <!-- Content column -->
    <div id="right_column_wrapper">

      <!-- Posts block -->
      <div id="right_column">

        <%= yield %>

        <!-- RSS feed block -->
        <div id="rss">
          <a href="#">SUBSCRIBE NOW <br /><span>to our RSS feed</span></a>
        </div>

      </div> <!-- End of Posts block-->

      <div class="clear"></div>

    </div> <!-- End of content section-->

    <div class="clear"></div>

    <!-- Footer -->
    <div id="footer">
      <p>The Ruby License is the <a href="http://en.wikipedia.org/wiki/Free_software_licence">free software licence </a> applied to the <a href="http://www.ruby-lang.org">Ruby programming language</a> and also available to be used in other projects.</p>
    </div>
    <div class="clear"></div>

  </div>
  <!-- END: wrapper -->
</div>

</div>  <!-- END: body wrapper -->
</body>
</html>

app/views/users/index.html.erb
<% @odd = true %>
<div id="users_list_holder">
  <div id="users_list_title">
    <div>
      Name
    </div>
    <div>
      Surname
    </div>
    <div>
      e-Mail adress
    </div>
  </div>
  <% @users.each do |user| %>
    <% if @odd %>
      <div class="single_user_data">
      <%  @odd = false   %>
    <% else %>
      <div class="single_user_data even">
      <% @odd = true %>
    <% end %>
      <div>
          <% if user.first_name %>
            <%= user.first_name %>
          <% else %>
            <p>-----</p>
          <% end %>
      </div>
      <div>
          <% if user.last_name %>
            <%= user.last_name %>
          <% else %>
            <p>-----</p>
          <% end %>
      </div>
      <div>
          <% if user.email %>
            <%= user.email %>
          <% else %>
            <p>-----</p>
          <% end %>
      </div>
    </div>
  <% end %>
</div>

app/views/users/new.html.erb
<div id="signup_holder">
  <h2>Create a new accaunt</h2>
  <%= form_for @user do |f| %>
    <% if @user.errors.any? %>
      <div class="error_messages">
        <h2>Form is invalid</h2>
        <ul>
          <% for message in @user.errors.full_messages %>
            <li><%= message %></li>
          <% end %>
        </ul>
      </div>
    <% end %>
      <div id="signup_labels">
        <div><%= f.label :email, "Enter your e-mail" %><br/></div>
        <div><%= f.label :password, "Enter Password" %><br/>  </div>
        <div><%= f.label :password_confirmation, "Confirm Password"%><br/> </div>
      </div>
      <div id="signup_forms">
        <div><%= f.text_field :email %><br/></div>
        <div><%= f.password_field :password %><br/></div>
        <div><%= f.password_field :password_confirmation %><br/></div>
      </div>
    <div id="create_user_button"><%= f.submit %></div>
  <% end %>
</div>

app/views/users/show.html.erb
<div id="signup_holder">
  <h2>Edit your new account</h2>
  <%= form_for @user, :url => set_name_url do |f| %>
      <% if @user.errors.any? %>
          <div class="error_messages">
            <h2>Form is invalid</h2>
            <ul>
              <% for message in @user.errors.full_messages %>
                  <li><%= message %></li>
              <% end %>
            </ul>
          </div>
      <% end %>
      <div id="signup_labels">
        <div><%= f.label :first_name, "First Name" %><br/></div>
        <div><%= f.label :last_name, "Last Name" %><br/>  </div>
        <div><%= f.label :email, "Your e-mail" %><br/>  </div>
      </div>
      <div id="signup_forms">
        <div><%= f.text_field :first_name %><br/></div>
        <div><%= f.text_field :last_name %><br/></div>
        <div><%= f.text_field :email %><br/></div>
      </div>
      <div id="create_user_button"><%= f.submit "Change" %></div>
  <% end %>
</div>